# Generated by Django 2.2.7 on 2020-03-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiGroup',
            fields=[
                ('id', models.IntegerField(auto_created=True,
                                           primary_key=True, serialize=False)),
                ('parentApiGroupId', models.IntegerField()),
                ('projId', models.IntegerField()),
                ('apiGroupName', models.CharField(max_length=32)),
                ('isEdit', models.BooleanField(default=False)),
            ],
        ),
    ]
