# Generated by Django 2.2.7 on 2020-03-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apigroup',
            options={'verbose_name': '接口分组表'},
        ),
        migrations.AlterField(
            model_name='apigroup',
            name='apiGroupName',
            field=models.CharField(max_length=32, verbose_name='接口分组名称'),
        ),
        migrations.AlterField(
            model_name='apigroup',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='apigroup',
            name='isEdit',
            field=models.BooleanField(default=False, verbose_name='是否可编辑，默认False'),
        ),
        migrations.AlterField(
            model_name='apigroup',
            name='parentApiGroupId',
            field=models.IntegerField(verbose_name='接口父分组id'),
        ),
        migrations.AlterField(
            model_name='apigroup',
            name='projId',
            field=models.IntegerField(verbose_name='项目id'),
        ),
    ]
