# Generated by Django 2.2.7 on 2020-03-26 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200326_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apigroup',
            name='parentApiGroupId',
        ),
    ]
