# Generated by Django 2.2.7 on 2020-03-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_apigroup_parentapigroupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apigroup',
            name='parentApiGroupId',
            field=models.CharField(max_length=54, verbose_name='接口父分组id'),
        ),
    ]
