# Generated by Django 2.2.7 on 2020-03-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200326_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiGroup1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projId', models.IntegerField(verbose_name='项目id')),
                ('apiGroupJson', models.CharField(max_length=4096, verbose_name='接口分组信息')),
            ],
            options={
                'verbose_name': '接口分组表1',
            },
        ),
    ]
