# Generated by Django 2.2.7 on 2020-03-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_apigroup1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiGroup1',
        ),
        migrations.RemoveField(
            model_name='apigroup',
            name='apiGroupName',
        ),
        migrations.RemoveField(
            model_name='apigroup',
            name='isEdit',
        ),
        migrations.RemoveField(
            model_name='apigroup',
            name='parentApiGroupId',
        ),
        migrations.AddField(
            model_name='apigroup',
            name='apiGroupJson',
            field=models.CharField(default='[{"id":1,"apiGroupName":"默认分组","isEdit":0}]', max_length=4096, verbose_name='接口分组信息'),
        ),
        migrations.AlterField(
            model_name='apigroup',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='apigroup',
            name='projId',
            field=models.IntegerField(unique=True, verbose_name='项目id'),
        ),
    ]
