# Generated by Django 2.2.7 on 2020-03-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200327_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projId', models.IntegerField(verbose_name='项目id')),
                ('apiGroupId', models.IntegerField(verbose_name='接口分组id')),
                ('apiSortNo', models.IntegerField(verbose_name='接口排序号')),
                ('apiName', models.CharField(max_length=64, verbose_name='接口名称')),
                ('apiPath', models.CharField(default='', max_length=64, verbose_name='接口地址')),
                ('apiProtocol', models.CharField(default='http', max_length=8, verbose_name='请求协议，http/https')),
                ('apiMethod', models.CharField(max_length=8, verbose_name='请求类型， GET/POST')),
                ('apiHeaders', models.CharField(default='[]', max_length=4096, verbose_name='请求头部信息，json格式')),
                ('apiQuerys', models.CharField(default='[]', max_length=4096, verbose_name='请求参数信息，json格式')),
                ('apiBody', models.CharField(default='[]', max_length=4096, verbose_name='请求body信息，json格式')),
                ('apiResp', models.CharField(default='[]', max_length=4096, verbose_name='请求返回信息示例，json格式')),
            ],
            options={
                'verbose_name': '接口表',
                'unique_together': {('projId', 'apiGroupId', 'apiSortNo'), ('projId', 'apiGroupId', 'apiName')},
            },
        ),
    ]
