# Generated by Django 2.2.7 on 2020-04-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_apis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apigroup',
            name='projId',
            field=models.BigIntegerField(unique=True, verbose_name='项目id'),
        ),
        migrations.AlterField(
            model_name='apis',
            name='apiGroupId',
            field=models.BigIntegerField(verbose_name='接口分组id'),
        ),
        # migrations.AlterUniqueTogether(
        #     name='apis',
        #     unique_together={('projId', 'apiGroupId', 'apiName')},
        # ),
    ]
