# Generated by Django 2.2.7 on 2020-04-17 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20200408_1454'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apis',
            unique_together={('projId', 'apiGroupId', 'apiSortNo')},
        ),
    ]
