# Generated by Django 2.2.7 on 2020-04-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20200417_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='apiBody',
            field=models.TextField(default='[]', max_length=409600, verbose_name='请求body信息，json格式'),
        ),
        migrations.AlterField(
            model_name='apis',
            name='apiResp',
            field=models.TextField(default='[]', max_length=409600, verbose_name='请求返回信息示例，json格式'),
        ),
    ]
